### ISSUE TITLE
bundle guzzle as dependency on deploy to TER

### ISSUE THREAD

**Issue by Aero91** [evoWeb/store_finder#22]
Right now, it's not possible to use this extension when TYPO3 isn't running in composer mode since guzzle is not installed.

**Comment by garbast** [comment]
If you would have taken your time to extract the latests 9.5.x version you would have seen that guzzled is packaged in the path vendor/guzzlehttp/guzzle

**Comment by Aero91** [comment]
You're right, but the extension relies on Guzzle 6 HTTP Adapter, which isn't shipped by TYPO3.
So the extension throws an error:
Class 'Http\Adapter\Guzzle6\Client' not found

**Comment by jrdeck** [comment]
@Aero91, did you find a workaround for this issue? It is a problem for us, too.

We are running 9.5.15 (currently the latest version of Typo3 9.x stream).

We have reviewed the [documentation for moving to compose](https://docs.typo3.org/m/typo3/guide-installation/master/en-us/MigrateToComposer/MigrationSteps.html), however, it is not trivial.

We have tried adding the [php-http/guzzle6-adapter](https://github.com/php-http/guzzle6-adapter) manually, but backed out as it was getting too messy.

We are happy to test out any debugging or development builds, in order to get this issue resolved. We can also provide any further logs or other information as required.

**Comment by garbast** [comment]
Sorry to say that, but Guzzle is not the only part you need. You also need to get geocoder-php/google-maps-provider working. You are realy better of with switching to composer based installation. It may seem to be difficulty at first but it's realy worth it.

My time is limited and i do not plan to work on including the packages in the build process. You could prepare a PR to get the build process including the missing packages, but if you are able to do that, you could also move on to composer installations.
