### ISSUE TITLE
LocationRepository::findByUidInBackend() must be of the type int, string given

### ISSUE THREAD

**Issue by vmandal** [evoWeb/store_finder#23]
Error while creating Store Location record in BE
Typo3 versions: typo3 9.5.16@dev, typo3 9.5.14
PHP Version 7.3.16

```
Oops, an error occurred!
Argument 1 passed to EvowebStoreFinderDomainRepositoryLocationRepository::findByUidInBackend() must be of the type int, string given, called in /typo3conf/ext/store_finder/Classes/Hook/TceMainHook.php on line 6
```

**Comment by wechselstroom** [comment]
This error happens when mysql strict mode is enabled. A quick fix is to add the following line to 
`$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']
`

`'initCommands' => 'SET SESSION sql_mode = \'NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION\';'`

**Comment by wechselstroom** [comment]
Another possible fix, if you don't want to disable strict mode is to override the TCA:

 `$GLOBALS['TCA']['tx_storefinder_domain_model_location']['columns']['latitude']['config']['default'] = 0;
    $GLOBALS['TCA']['tx_storefinder_domain_model_location']['columns']['longitude']['config']['default'] = 0;`
